# Generated by Django 5.2.1 on 2025-05-21 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0008_scooter_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, help_text='Store this staff member is assigned to. Leave blank for admins or staff with access to all stores.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='inventory.store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
