# Generated by Django 5.2 on 2025-05-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='scooter',
            name='category',
            field=models.CharField(choices=[('A', 'Category A - Sym Orbit 125cc'), ('B', 'Category B - Jet 14 200cc'), ('C', 'Category C - Citycom 300cc'), ('D', 'Category D - Vespa 150/300cc')], default='A', max_length=1),
        ),
    ]
