# Generated by Django 5.2 on 2025-05-23 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_scooter_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Default store for all purchase items', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.store'),
        ),
    ]
